# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: TUF15xveili@protonmail.com
author_name: jizen
contract_name: vote_chain
deployment_language: python
preset_name: production
project_name: VoteChain-contracts

