# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.14
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: TUF15xveili@protonmail.com
author_name: jizen
cloud_provider: none
contract_name: vote_chain
deployment_language: python
preset_name: production
project_name: VoteChain

